# Generated by Django 2.1.5 on 2019-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='push_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
