# Generated by Django 2.1.5 on 2019-06-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'NEW'), (1, 'ACCEPTED'), (2, 'REJECTED'), (10, 'DRIVER_RECOMENDED'), (20, 'DRIVER_ARRIVED'), (100, 'CANCEL'), (200, 'COMPLETED')], default=0),
        ),
    ]
