# Generated by Django 2.1.5 on 2019-01-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='gearType',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'AUTO'), (2, 'MANUAL')], default=2),
        ),
    ]
