# Generated by Django 2.1.5 on 2019-05-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_userinfo_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='push_token',
        ),
    ]
