# Generated by Django 2.1.5 on 2019-06-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20190609_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='Document',
        ),
        migrations.RemoveField(
            model_name='driverhistory',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='travelhistory',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='driverhistory',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driverhistory_driver_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driverlocation_driver_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_driver_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_driver_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='travelhistory_driver_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
